from . import patient
from . import examination
from . import appointment
from . import vitals
from . import prescription
from . import dashboard
from . import livechat
from . import res_users
from . import mail_message
